# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

tasks:
  test:
    desc: Runs the tests
    cmd: go test ./...

  bench:
    desc: Runs the benchmarks
    cmd: go test -bench . -benchmem

  format:
    desc: Formats Go code
    cmd: go fmt ./...

  lint:
    desc: Lints Go code
    cmd: go vet ./...

  check:
    desc: Formats and lints Go code
    cmd: task format lint
