name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: true

      # Tools installed with Devbox are not added to the PATH. Prefix commands
      # with `devbox run` to invoke them correctly.
      - run: devbox run task test
